### ISSUE TITLE
Add a link for Docs 'Overview' section on /documentation

### ISSUE THREAD

**Issue by souperneon** [mapzen/documentation#175]
I don't see https://www.mapzen.com/documentation/overview/ linked from anywhere on https://www.mapzen.com/documentation/. That page is super useful!

**Comment by rmglennon** [comment]
Oh no, you can't find it @souperneon! 

The Get Started button goes there in the top. Let's talk about how we can make it more obvious. Should it go in the list too?

**Comment by souperneon** [comment]
oh ha! That looks like the CTA to get a key in other places, so I ignored it :( 
Maybe we can try making the button text more specific?

**Comment by rmglennon** [comment]
closed by #283
