### ISSUE TITLE
change all api key/rate limit pages to link to documentation/overview

### ISSUE THREAD

**Issue by kkowalsky** [mapzen/documentation#192]
because updating things is hard, we should change the 'api-keys-rate-limits.md' file to link to the documentation overview page to prevent huge changes to a bunch of docs repos

**Comment by rmglennon** [comment]
[ ] mapzen.js

**Comment by rmglennon** [comment]
@kkowalsky - these should all be ready for review when you want to look. The remaining item is the old Tangram tutorial, which we can talk about because it needs some other updates.

Thanks!

**Comment by kkowalsky** [comment]
closing this issue and moving tangram into another issue
