### ISSUE TITLE
Some mobility doc links in index.md are broken

### ISSUE THREAD

**Issue by rmglennon** [mapzen/documentation#211]
Some links in index.md are broken, and it doesn't really make sense. I'm sure these worked before because I would have tested the homepage.

`[Mapzen Turn-by-Turn](turn-by-turn-overview.md)` tries to link to
https://mapzen.com/documentation/mobility/turn-by-turn-overview.md
when it should go to
https://mapzen.com/documentation/mobility/turn-by-turn/overview/

`[Optimized Route service](optimized_route/api-reference.md)` tries to link to
https://mapzen.com/documentation/mobility/optimized_route/api-reference.md
when it should go to
https://mapzen.com/documentation/mobility/optimized/api-reference/

works
`(matrix/api-reference)` 

This is odd because index.md is in the same structure as turn-by-turn-overview, and links should use the .md extension. Also, this shows that the mz-redirects work to send everything to a mobility URL, but not the mz-renames to change the optimized_route folder name.

Spotted by @randymeech.

**Comment by migurski** [comment]
Hm, these are all [ones that we rename in the Mobility config](https://github.com/mapzen/mapzen-docs-generator/blob/master/config/mobility.yml#L5-L18).

**Comment by migurski** [comment]
So we have options.

1. Continue on the rename-train and make our code smarter about following names around.
2. Take a hint and change the paths upstream.

**Comment by rmglennon** [comment]
See also https://github.com/valhalla/valhalla-docs/issues/127

to reorganize the content.
