### ISSUE TITLE
Complete upstream docs notifications

### ISSUE THREAD

**Issue by migurski** [mapzen/documentation#224]
Prepare pull requests with Circle notifications in these upstream documentation repositories:

- [x] [Tangram](https://github.com/tangrams/tangram-docs/pull/167)
- [x] [Metro Extracts](https://github.com/mapzen/metro-extracts/pull/286)
- [x] [Valhalla](https://github.com/valhalla/valhalla-docs/pull/131)
- [x] [Vector Tiles](https://github.com/tilezen/vector-datasource/pull/1119)
- [x] [Terrain Tiles](https://github.com/tilezen/joerd/pull/114)
- [x] [Search](https://github.com/pelias/pelias-doc/pull/165)
- [x] [Android](https://github.com/mapzen/android/pull/228)
- [x] [iOS](https://github.com/mapzen/ios/pull/93)
- [x] [Mapzen.js](https://github.com/mapzen/mapzen.js/pull/291)
- [x] [Libpostal](https://github.com/whosonfirst/go-whosonfirst-libpostal)

Follow-up to #223.

**Comment by migurski** [comment]
🎉 50% done! 🎉

**Comment by migurski** [comment]
💥 90% done! 💥

**Comment by nvkelso** [comment]
(Cartography Docs has been added to CircleCI flow now.)

**Comment by rmglennon** [comment]
Libpostal has the "beacon". These are all done.

https://github.com/whosonfirst/go-whosonfirst-libpostal/pull/3
