### ISSUE TITLE
Update circle tickle for new documentation repo name

### ISSUE THREAD

**Issue by nvkelso** [mapzen/documentation#243]
Prepare pull requests with Circle notifications in these upstream documentation repositories:

- **Tangram**
  - [x] Add: https://github.com/tangrams/tangram-docs/pull/183
  - [x] Cleanup: https://github.com/tangrams/tangram-docs/pull/185
- **Metro Extracts**
  - [x] Add: https://github.com/mapzen/metro-extracts/pull/292
  - [x] Cleanup: https://github.com/mapzen/metro-extracts/pull/293
- **Valhalla**
  - [x] Add: https://github.com/valhalla/valhalla-docs/pull/143
  - [x] Cleanup: https://github.com/valhalla/valhalla-docs/pull/144
  - [x] CIRCLE_TOKEN
- **Vector Tiles**
  - [x] Add: https://github.com/tilezen/vector-datasource/pull/1156
  - [x] Cleanup: https://github.com/tilezen/vector-datasource/pull/1159
- **Terrain Tiles**
  - [x] Add: https://github.com/tilezen/joerd/pull/123
  - [x] Cleanup: https://github.com/tilezen/joerd/pull/124
- **Search**
  - [x] Add: https://github.com/pelias/pelias-doc/pull/174
  - [x] Cleanup: https://github.com/pelias/pelias-doc/pull/176
  - [x] CIRCLE_TOKEN
- **Android**
  - [x] Add: https://github.com/mapzen/android/pull/265
  - [x] Cleanup: https://github.com/mapzen/android/pull/272
- **iOS**
  - [x] Add: https://github.com/mapzen/ios/pull/149
  - [x] Cleanup: https://github.com/mapzen/ios/pull/151
- **Mapzen.js**
  - [x] Add: https://github.com/mapzen/mapzen.js/pull/341
  - [x] Cleanup: https://github.com/mapzen/mapzen.js/pull/344
- **Libpostal**
  https://github.com/whosonfirst/go-whosonfirst-libpostal
  (But CircleCI isn't setup yet on libpostal)
- **Cartography**
  https://github.com/tangrams/cartography-docs/
  (But CircleCI isn't setup yet on Cartography docs)

Where Cleanup means that we have gone in to remove the old repo name in the circle.yml after we rename mapzen-docs-generator to documentation.
  

Follow-up to #223 and #224.

**Comment by migurski** [comment]
We are expecting to change the name of this repository to "documentation", so we’d need to update the `tickle-circle` line in `circle.yml` for each of those repos to point to the new name. Best approach would be to _add_ a new line, then change the repo name, then remove the old line for each. This would make it possible to take a fig bar break of undetermined length during a process which might take a week or two.

**Comment by rmglennon** [comment]
Also need to change the Environment Variable in each repo in Circle to my token.

**Comment by migurski** [comment]
Just waiting on Vector Tiles now! Then we can rename this repo freely.

**Comment by nvkelso** [comment]
Vector tiles has been merged, renaming can commence.

**Comment by migurski** [comment]
@rmglennon did the big rename!

**Comment by migurski** [comment]
We had some odd cache failures in Circle that turned out to also involve a missing installation step here. Fixed in https://github.com/mapzen/documentation/pull/248, now waiting for the PRs above to be approved by each team.

**Comment by nvkelso** [comment]
Added note that Cartography docs doesn't have CircleCI integration yet, either (same as Libpostal).

**Comment by rmglennon** [comment]
These are all fixed!

**Comment by rmglennon** [comment]
@nvkelso added CircleCI to cartography docs, now only Libpostal needs it.
