### ISSUE TITLE
Rate Limit time window

### ISSUE THREAD

**Issue by davidbarratt** [mapzen/documentation#265]
The documentation says there is a per-second and per-day limit:
https://github.com/mapzen/documentation/blob/master/docs/overview/index.md

However, it doesn't say (that I can find) if the second is 1000 milliseconds (from initial request less than 1000 milliseconds ago, i.e. if I make 6 requests at millisecond 999 I must wait 999 milliseconds before making another request) or if it's a literal second and count is reset when going from 00:00:00 to 00:00:01 (i.e. if I make 6 requests at millisecond 999, I must wait 1 millisecond before making another request)?

Likewise, is the day limit 24 hours (from initial request less than 24 hours ago, i.e if I make 30,000 requests at 23:59 I must wait 23 hours and 59 minutes before making another request) or does it start and end at 00:00 (i.e. if I make 30,000 request at 23:59, I must wait 1 minute before making another request)? If so, what timezone? UTC?

Could you clarify this?

**Comment by rmglennon** [comment]
Hello @davidbarratt - thanks for the comment. Currently, you can think of the limits as "rolling", where older requests drop-off after the time interval passes. If you are encountering rate limits or have more questions like this, send a note to hello at mapzen dot com so we can help you.

**Comment by rmglennon** [comment]
Effective June 1, 2017, accounts will move to monthly rate limits. 

When that happens, rate limits are reset on the first day of every month at 00:00 UTC (Coordinated Universal Time).

More information: https://mapzen.com/pricing/
