### ISSUE TITLE
redesign docs overview page

### ISSUE THREAD

**Issue by kkowalsky** [mapzen/documentation#281]
- [x]  finish wireframes (@souperneon)

- [x] goal to update formatting for '/overview' page for pricing details to be 'Get Started' (@kkowalsky)

- [x] redesign div for mapzen.com/documentation & developer dashboard (@kkowalsky)

- [x]  add detailed content for 'Get Started' steps (@rmglennon)

- [x]  pick out FAQs for both main pricing and pricing docs, create answers (@kkowalsky/@rmglennon)

**Comment by souperneon** [comment]
**Pricing page**
![mapzen_pricing_4 1](https://cloud.githubusercontent.com/assets/6125224/24819640/742c5548-1bb3-11e7-9c8e-e6032a71baa7.png)

**Get started with Mapzen Flex page**
![mapzen_pricing_4 2](https://cloud.githubusercontent.com/assets/6125224/24819639/742adf88-1bb3-11e7-8de0-72786dfe6255.png)

**Comment by souperneon** [comment]
@rmglennon let's make sure we add a question in the FAQ's on the pricing page about other Mapzen services coming soon to Flex.

**Comment by rmglennon** [comment]
fixed with #283
