### ISSUE TITLE
Heading stylings translated from # in markdown are too large

### ISSUE THREAD

**Issue by rmglennon** [mapzen/documentation#285]
Traditionally, we've used one # for the top heading and ## and ### for additional headings on a markdown page. With recent style guide updates, this looks too large on the page. Perhaps we take # down to H2 or maybe even H3 and so on.

This came up in comments in https://github.com/mapzen/documentation/pull/283. Adding here because it's an issue across all docs.

![image](https://cloud.githubusercontent.com/assets/4380498/25164904/788140d0-2488-11e7-938f-6428f0ec56a2.png)

**Comment by rmglennon** [comment]
@rfriberg noted that the documentation pages have two `<h1>` tags on them, one for the text in the top banner and one for the first heading on the page. This can cause some search engine optimization issues.

"An ideal H1 will be specific and relevant to the page. What we could do is make the banner text a different heading tag and make the first (actual) heading on the page an H1 (shrunk down a bit if that's what's desired)."

**Comment by rfriberg** [comment]
@rmglennon - I'm trying to assign this to @meghanhade .  Does she need to be added to some user list on this repo?

**Comment by meghanhade** [comment]
👋 I'm here to help

**Comment by rmglennon** [comment]
see https://precog.mapzen.com/mapzen/documentation/meghan-heading-styling/documentation/overview/ for a preview

**Comment by meghanhade** [comment]
The styleguide changes are in this PR: https://github.com/mapzen/styleguide/pull/477

**Comment by rfriberg** [comment]
Preview looks good.  My only concern is that we now have the same font size (24px) for both h2 and h3 (except on mobile).

**Comment by meghanhade** [comment]
@rfriberg I'll fix that.

**Comment by meghanhade** [comment]
@rfriberg @rmglennon I bumped the h3 font-size down and added in the padding-top for the documentation-header as well. These changes are on the meghan-heading-styling branch.

**Comment by rfriberg** [comment]
Looks good to me. Thanks!

**Comment by rmglennon** [comment]
Thanks @meghanhade. pull request when ready!

**Comment by meghanhade** [comment]
@rmglennon @rfriberg Final step--now that this styling has been merged in on the styleguide, I've removed the hard-coded css from the documentation file. If you could take one last look and approve, I'll merge.

**Comment by rmglennon** [comment]
fixed over in https://github.com/mapzen/styleguide/pull/477
