### ISSUE TITLE
search linking to old/nonexistent page?

### ISSUE THREAD

**Issue by meetar** [mapzen/documentation#295]
Using the search bar on the documentation site to search for "filters" returns this search:

https://www.google.com/search?as_sitesearch=mapzen.com%2Fdocumentation&q=filters

Which has as the second result a link to this page:

https://mapzen.com/documentation/tangram/filters/

Which is not in Tangram's documentation source repo: https://github.com/tangrams/tangram-docs/

I don't know where it's coming from. Maybe it's an old version of this page?
 https://github.com/tangrams/tangram-docs/blob/gh-pages/pages/Filters-Overview.md

Regardless, afaik it shouldn't be in the search results – maybe an underlying issue is that the build process doesn't remove pages which are no longer being built or referenced in https://github.com/mapzen/documentation/blob/master/config/tangram.yml ?

**Comment by rmglennon** [comment]
Thanks for the report. We've done almost nothing with the search, and what works is pretty much luck. :(

tying this one to https://github.com/mapzen/documentation/issues/158

**Comment by rmglennon** [comment]
This is still reproducible. Our docs just use a plain Google search engine (vs Google Site Search, which is paid and allows ads and Google branding to be removed) for the box.

You can find the same page by doing a regular Google search for `tangram filters`. I am investigating, but it looks like the only way to get rid of it is to fill out a form to request Google remove it from its cache.

![image](https://user-images.githubusercontent.com/4380498/32472131-d2004396-c315-11e7-9e00-3f292b220017.png)
