### ISSUE TITLE
Update API key placeholder text throughout to "your-mapzen-api-key"

### ISSUE THREAD

**Issue by rmglennon** [mapzen/documentation#310]
This text is used to replace the placeholder text with the user's actual API key when signed in on the website.

These need updating:
- [x] Android - https://github.com/mapzen/android/pull/404 (has issues)
- [x] Cartography - https://github.com/tangrams/cartography-docs/pull/30 (has issues)
- [x] iOS - https://github.com/mapzen/ios/pull/336 (OK)
- [x] terrain tiles - https://github.com/tilezen/joerd/pull/147 (OK)
- [x] vector tiles - https://github.com/tilezen/vector-datasource/pull/1275 (OK) (merged, now in a release)
- [x] Who's on First - Docs are generated, but updated to work. (OK)

These use this style, but may need some content edits, too:
- [x] mapzen.js - https://github.com/mapzen/mapzen.js/pull/399 (OK) (merged, now in a release)
- [x] mobility - https://github.com/valhalla/valhalla-docs/pull/177 (has issues)
- [x] search (links and tutorial) - https://github.com/pelias/pelias-doc/pull/199 (OK)

**Comment by rmglennon** [comment]
We should go ahead and merge the content changes. Remaining issues with the code for the swapping process are being tracked in https://github.com/mapzen/documentation/issues/312.

**Comment by nvkelso** [comment]
**Cartography** and **terrain tile** changes are live on `mapzen.com/documentation`, but while **vector-datasource** has been merged to master it'll require some finagling to do a special release. Please ping me when this is closer to all going live and I'll do that release management.
